entero numero
entero suma

inicio
	suma<-0
	numero<-1
	escriba "escriba numero para suma:"
		lea suma
		llamar nueva_linea 
	escriba "escriba numero para numero:"
		lea numero
		
	mientras (numero<=10) haga
	 escriba "el numero es:", numero
	 suma<-suma+numero
	 numero<-numero+1
	 llamar obtener_caracter
	  llamar nueva_linea
	 escriba "la suma es:", suma
	llamar nueva_linea
	fin mientras 
 escriba"la suma total es:", suma

fin