real a,b,c
inicio
	escriba "Sumando dos numeros ingresados por teclado"
	llamar nueva_linea
	llamar nueva_linea
	escriba "ingrese el primer numero:  "
	lea a
	llamar nueva_linea
	escriba "ingrese el segundo numero: "
	lea b
	llamar nueva_linea
	c <- a+b
	escriba "La suma de ",a," mas ",b," es:  ",c
	llamar nueva_linea
	llamar nueva_linea
	escriba "La suma de a que es ",a," mas b que es ",b," es: ",c
fin